blank_issues_enabled: false
contact_links:
  - name: control-loss support
    url: https://github.com/control-toolbox/control-loss/discussions
    about: Please ask and answer questions about control-loss here.
  - name: Control-toolbox organisation support
    url: https://github.com/orgs/control-toolbox/discussions
    about: For more general questions about control-toolbox ecosystem it's here.
