blank_issues_enabled: false
contact_links:
  - name: LossControl.jl support
    url: https://github.com/control-toolbox/LossControl.jl/discussions
    about: Please ask and answer questions about LossControl.jl here.
  - name: Control-toolbox organisation support
    url: https://github.com/orgs/control-toolbox/discussions
    about: For more general questions about control-toolbox ecosystem it's here.
